### ISSUE TITLE
when expanding cell crash

### ISSUE THREAD

**Issue by kjoe07** [gringoireDM/LNZTreeView#11]
if modified the demo example to use an array of data parsed from json using codable. the tree show the parenst node perfect but when selecting the first parent or any parent in the second child get crash with unexpectedly foun nil at indexPathForNode(withIdentifier: node.identifier, inSection: section) the node idetifier should be in a format "as123458978456asdd" as parsed from json. 
[Archivo.zip](https://github.com/gringoireDM/LNZTreeView/files/2241598/Archivo.zip) heres is the example and using. the rare thing is the demo works well with numbers as identifier but with this strign it cannot find the node.

**Comment by Pirokar** [comment]
Did you find a solution? The same problem
