### ISSUE TITLE
Swift 4.2: UITableViewCellEditingStyle must change to UITableViewCell.EditingStyle

### ISSUE THREAD

**Issue by dreampowder** [gringoireDM/LNZTreeView#12]
In swift 4.2, the compiler does not compile because of UITableViewCellEditingStyle attributes. Those attributes must change to UITableViewCell.EditingStyle

**Comment by kuemme01** [comment]
@dreampowder The Owner already updated to swift version 4.2 but not yet updated the pod.
You can reach the swift 4.2 version via:
`pod 'LNZTreeView', :git => 'https://github.com/gringoireDM/LNZTreeView.git', :branch => 'swift_4_2'`

For any reason pod `'LNZTreeView', '~> 1.1.2'` doesn't work.

Would be nice if you can update your pod @gringoireDM

**Comment by dreampowder** [comment]
thanks for the info @kuemme01

**Comment by gringoireDM** [comment]
@kuemme01 I had a couple of very busy months. I'll update the pod today. :) Sorry for the delay.

**Comment by kuemme01** [comment]
What a nice christmas present! I don't expected that so early! Thanks man and have nice holidays! =)
