### ISSUE TITLE
enhancement - filter by string

### ISSUE THREAD

**Issue by johndpope** [gringoireDM/LNZTreeView#4]
<img width="276" alt="screen shot 2018-02-19 at 11 23 00 am" src="https://user-images.githubusercontent.com/289994/36387555-44ca5bb6-1567-11e8-8b5f-117e86515907.png">

need to trawl through the root node for matches.
https://github.com/bfeher/SceneKit-COLLADA-Demo/pull/2

**Comment by gringoireDM** [comment]
I'm sorry, but I don't understand your request.

**Comment by johndpope** [comment]
So it would be neat if there was an integrated textfield that would apply a filter to the tree and just show results.

**Comment by gringoireDM** [comment]
This is a logic that should be in your datasource. This library simply provides a TreeView. Which are the data displayed by this view are responsibility of the datasource, so if there is any filtering logic you would like to adopt that must be on the implementation side, not on the library.

**Comment by johndpope** [comment]
@gringoireDM - it is possible using protocol

found this today - 
https://github.com/onekiloparsec/KPCSearchableOutlineView


```swift

//
//  SearchableNode.swift
//  KPCSearchableOutlineView
//
//  Created by Cédric Foellmi on 11/12/2016.
//  Copyright © 2016 onekiloparsec. All rights reserved.
//

import Foundation

extension IndexPath {
    func indexPathByAddingIndexInFront(_ index: Int) -> IndexPath {
        let indexPath = IndexPath(index: index)
        return indexPath.appending(self)
    }
}

public protocol SearchableNode: NSObjectProtocol {
    var uuid: UUID { get }
    var childNodes: [SearchableNode] { get set }
    var originalChildNodes: [SearchableNode] { get set }
    var parentNode: SearchableNode? { get }
    func searchableContent() -> String
}

public extension Collection where Iterator.Element == SearchableNode {
    func indexOf(_ element: Iterator.Element) -> Index? {
        return index(where: { $0.uuid == element.uuid })
    }
}

public extension SearchableNode {
    
    func indexPath() -> IndexPath {
        var indexPath = IndexPath()
        var activeNode: SearchableNode = self

        while activeNode.parentNode != nil {
            if let index = activeNode.parentNode!.childNodes.indexOf(self) {
                indexPath = indexPath.indexPathByAddingIndexInFront(index)
                activeNode = activeNode.parentNode!
            }
            else {
                break
            }
        }
        
        return indexPath
    }
}
```

**Comment by gringoireDM** [comment]
I never said it's not possible. I said that it is not what I'm proposing for this library. what this library does and wants to do is to give a generic Tree View for iOS. **Not** filtering through its data source. The feature is implementable on the client side, where the library is actually used. 

Feel free to extend the features of this class in you project, but I will not add this feature in the main project. This library does not manipulate the dataSource.
