### ISSUE TITLE
tree.ViewSelect(node: 

### ISSUE THREAD

**Issue by hughesyadaddy** [gringoireDM/LNZTreeView#7]
Great job with the code. I'm modifying to for selecting a node on ViewDidLoad and trying to figure out how to use the function you have. I've tried creating a class that matches TreeNodeProtocol but can't seem to figure out how to save and feed a specific protocol object into this function.

**Comment by gringoireDM** [comment]
Hi, can you give more info about what you are trying to achieve? I don't really have clear the use case, sorry.

**Comment by hughesyadaddy** [comment]
Thank you. Played with the code and figured out what I needed! Much appreciated and great work on the tree View Node.
