### ISSUE TITLE
Set rows height

### ISSUE THREAD

**Issue by rursache** [gringoireDM/LNZTreeView#9]
how can i set rows height?

**Comment by gringoireDM** [comment]
Hi, currently you can't.

**Comment by rursache** [comment]
adding the cell height tableview delegate in your library caused crashes on the first 2 rows each time i expanded them :(

however, i managed to successfully apply a walkaround: i set my cell in a XIB, where i added a height-constraited UIView, as a container of all my cell elements.

**Comment by gringoireDM** [comment]
Hi, It's not a safe way of doing it. It should be done either by creating a new var (and change the equivalent var of the underlying tableview) or by adding a delegate method that proxies the UITableview delegate method.

**Comment by rursache** [comment]
i tried to proxy it but the result was the one above: always crashing on cell 1 and 2 on expand. i can provide some logs tomorrow morning.

thanks for your time and help

**Comment by gringoireDM** [comment]
Hi, I added this feature in version 1.1.1 now published. pod update. 

Sorry for taking so long.
